---
azure-hosts:
  hosts:
    devops-vm-1:
      ansible_host: az-devops
    devops-vm-2:
      ansible_host: service-vm

db-servers:
  hosts:
    db-server:
      ansible_host: db-vm

local-vms:
  hosts:
    local-vm-1:
      ansible_host: local-db